### ISSUE TITLE
swipe to dismiss ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ersin-ertan** [jaychang0917/SimpleRecyclerView#10]
Standard implementation with `recyclerView.enableSwipeToDismiss(swipeToDismissCallback, LEFT, RIGHT);` crashing after element is swiped.

**Comment by jaychang0917** [comment]
pls provide the error log, android version, library version.

**Comment by jaychang0917** [comment]
Thanks your report, Should be fixed in the new release `1.1.5`.
