### ISSUE TITLE
Multi type viewholder casting crash

### ISSUE THREAD

**Issue by ersin-ertan** [jaychang0917/SimpleRecyclerView#13]
See this branch - https://github.com/ersin-ertan/Recycler/tree/multiTypeCrash

I'm testing two different types, TextCell and TextCell2, each of which uses their own data model of Text and Text2, respectively. 

Press ADD to add a new TextCell2 to the list - > crash

`java.lang.ClassCastException: com.nullcognition.recycler.TextCell2$ViewHolder cannot be cast to com.nullcognition.recycler.TextCell$ViewHolder
                                                                              at com.nullcognition.recycler.TextCell.onBindViewHolder(TextCell.java:15)`

**Comment by jaychang0917** [comment]
I think it is because that your two cells are using the same layout resource, try with different layout resource solve the problem. 

Please feel free to reopen this issue if your have further question.
