### ISSUE TITLE
Empty state view does not appear when the recycler view is initially empty

### ISSUE THREAD

**Issue by dyancat** [jaychang0917/SimpleRecyclerView#17]
If you create a SimpleRecyclerView with an empty state view, it doesn't show the empty state view unless you add items first then remove them later.

I replicated with the sample project. If `loadBookingsFromNetwork()` is removed from the onCreate of EmptyStateViewActivity.java:
```
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_empty_view);
    ButterKnife.bind(this);

    init();
    //loadBooksFromNetwork();
  }
```

Then when the activity is opened, the empty state view is not shown. Once you hit add then remove all, it will appear.

**Comment by jaychang0917** [comment]
Hi @dyancat , it is because the empty state checking is only applied when there is data changed. If you want to show the empty state view explicitly, you can set `srv_showEmptyStateView` to `true`, which is added in `1.1.8`. Pls refer [Empty State View](https://github.com/jaychang0917/SimpleRecyclerView#empty_view).

**Comment by jaychang0917** [comment]
Please feel free to reopen the issue if you have any questions.

**Comment by dyancat** [comment]
Hi I just gave it a go, it doesn't appear to be working

Debugging through, it seems like when I set the srv_showEmptyStateView to true, it calls SimpleRecyclerView showEmptyStateView(), which adds the empty state view cell. But the addCell call also triggers a call to updateEmptyStateViewVisibility() which hides the empty view immediately

**Comment by jaychang0917** [comment]
Sorry, I don't get your meaning. `addCell` will hide the empty view, isn't it? Can you describe your expect result and the actual result?

**Comment by dyancat** [comment]
Hi it looks like I was misunderstanding the issue.

The empty state view is shown with this new fix, but my code which updates the recycler view calls removeAllCells, then addCells. This results in no empty state view being shown if the cells list passed to addCells is empty. Not sure if this is expected behaviour but it's easy enough to workaround

Cheers
