### ISSUE TITLE
getAllCells after updateCell returning stale data

### ISSUE THREAD

**Issue by ersin-ertan** [jaychang0917/SimpleRecyclerView#19]
`getCell` and `getAllCells` are not updated. 

I verified this with break points showing that the two get calls will occur before the `MyCell.onBindViewHolder` with the `changedPayload`, even when `updateCell` is called before the two gets.

```java
recyclerView.updateCell(1, new Text("1000", 0));

        Log.i("GETAFTERUPDATE", ((TextCell) recyclerView.getCell(1)).getItem().text);

        int total = 0;
        for (SimpleCell sc : recyclerView.getAllCells()) {
```

**Comment by jaychang0917** [comment]
Yes, `updateCell()` will not update the bound data of cell. If you want to update the bound data, you should call `cell.setItem(newItem)`.
