### ISSUE TITLE
Support for this type ？

### ISSUE THREAD

**Issue by AndMy** [jaychang0917/SimpleRecyclerView#20]
![ftnnf 1_4kq _1 1_x9 p](https://cloud.githubusercontent.com/assets/7222340/23699470/3492c08e-042a-11e7-9a56-c53017b0d8bc.png)

**Comment by jaychang0917** [comment]
Hi, it is not support yet.

**Comment by jaychang0917** [comment]
The workaround is that you can use `grid` layout mode, and treat each element as a cell.

**Comment by jaychang0917** [comment]
As duplicated with [#16](https://github.com/jaychang0917/SimpleRecyclerView/issues/16), i close this.

**Comment by AndMy** [comment]
Thank you  jaychang0917. I think I like you
