### ISSUE TITLE
addOrUpdateCells fails on an empty RecyclerView

### ISSUE THREAD

**Issue by gouravd** [jaychang0917/SimpleRecyclerView#21]
it seems that addOrUpdateCells() fails/crashes when the SimpleRecyclerView is empty. 

at some point, the SimpleRecyclerView code checks for the mapping of type/name and since the recyclerview isempty (addCell or addCells not called) it crashes.

As a workaround, I have to add a dummycell at the initialization

**Comment by jaychang0917** [comment]
Hi @gouravd , can you provide crash log?

**Comment by jaychang0917** [comment]
Thanks your report, this bug should be fixed in the new release `1.1.9`.

Please feel free to reopen the issue if you have any questions.
