### ISSUE TITLE
Is there a way to "Pull-To-Refresh" in SimpleRecyclerView

### ISSUE THREAD

**Issue by gouravd** [jaychang0917/SimpleRecyclerView#22]
Is there a way to "Pull-To-Refresh" in SimpleRecyclerView?

**Comment by jaychang0917** [comment]
No, you can use existing "Pull-To-Refresh" library as a plugin since SimpleRecyclerView is just a RecyclerView.

**Comment by jaychang0917** [comment]
Please feel free to reopen the issue if you have any questions.
