### ISSUE TITLE
Item show not correct

### ISSUE THREAD

**Issue by huylv177** [jaychang0917/SimpleRecyclerView#23]
When i scroll my recycler view to end and scroll again to top, some item in the top change and become not correct. Please tell me if i miss something. Thank you!

**Comment by jaychang0917** [comment]
Hi @huylv177 any sample code?

**Comment by huylv177** [comment]
Please take a look ![H](https://farm3.staticflickr.com/2938/33410766892_ae224e53ab_h_d.jpg)

**Comment by jaychang0917** [comment]
I can't get any clue from your code, perhaps you need to provide a sample project that can reproduce this issue for me to check.

**Comment by huylv177** [comment]
Here is the sample https://github.com/huylv177/JustADraft

**Comment by jaychang0917** [comment]
Hi @huylv177 Sorry for late reply as i am very busy these few days. In your `BookCell`, try return the `imageId`.  I try to investigate why returning 0 cause this issue later, but this workaround should fix your problem.
```java
@Override
    protected long getItemId() {
        return getItem().imageid;
    }
```
