### ISSUE TITLE
Bug in removeCells?

### ISSUE THREAD

**Issue by gouravd** [jaychang0917/SimpleRecyclerView#24]
public void removeCells(int fromPosition, int toPosition) {
        for(int i = fromPosition; i <= toPosition; ++i) {
            SimpleCell cell = (SimpleCell)this.cells.get(i);
            this.cells.remove(cell);
            this.removeCellType(cell);
        }

        this.notifyItemRangeRemoved(fromPosition, toPosition - fromPosition + 1);
    }

isin't this always going to crash (Outofrange Index exception) at the position ((toPos - fromPos / 2) + 1)? Because this,cells is mutating..

We should replace SimpleCell cell = (SimpleCell)this.cells.get(i); with SimpleCell cell = (SimpleCell)this.cells.get(fromPosition);

or simply delete reverse

      for(int i = toPosition; i >= fromPosition; i--) {
            SimpleCell cell = (SimpleCell)this.cells.get(i);
            this.cells.remove(cell);
            this.removeCellType(cell);
        }

**Comment by jaychang0917** [comment]
Ya, you are correct, thanks for your contribution.
