### ISSUE TITLE
Reloading SimpleRecyclerView causes extra cells

### ISSUE THREAD

**Issue by csimmonsbluebook** [jaychang0917/SimpleRecyclerView#27]
When I hit a refresh button in my app to reload the SimpleRecyclerView with section headers, I use an AsyncTask to get the data to create the sections and cells. I run the .removeAllCells() onPreExecute, create the cells in the doInBackground, and add the cells to the recylerView in the onPostExecute. However, the recyclerView seems to do some sort of caching and adds an extraneous section to the beginning and then adds an extraneous cell to the end of each section after each refresh.

I've added images below for reference:

On initial load...
![screenshot_20170602-125143](https://cloud.githubusercontent.com/assets/19786779/26736157/e7a3724e-4792-11e7-9f9c-b35651a2a3e9.png)

After first refresh...
![screenshot_20170602-125148](https://cloud.githubusercontent.com/assets/19786779/26736163/ed735db0-4792-11e7-9513-e5a74c8a5b38.png)

After second refresh...
![screenshot_20170602-125153](https://cloud.githubusercontent.com/assets/19786779/26736171/f2883e9c-4792-11e7-977f-ba138e46cc31.png)

You can see the pattern, and it continues with each refresh. Any thoughts on how to solve this issue? Thanks

**Comment by jaychang0917** [comment]
Can you provide a simple demo project that can reproduce your issue?

**Comment by csimmonsbluebook** [comment]
@jaychang0917 I've posted an example showing the same issue at https://github.com/csimmonsbluebook/SimpleRecyclerViewTest

**Comment by jaychang0917** [comment]
@csimmonsbluebook You should call `setupRecyclerViewHeaders();` in on `onCreate`

**Comment by csimmonsbluebook** [comment]
@jaychang0917 That still didn't fix the issue when refreshing the recyclerView. After refreshing, it still creates the extraneous section and cells.

**Comment by jaychang0917** [comment]
@csimmonsbluebook what's your new code? pls update https://github.com/csimmonsbluebook/SimpleRecyclerViewTest

**Comment by csimmonsbluebook** [comment]
@jaychang0917 Sorry I moved the wrong method call. But moving `setupRecyclerViewHeaders();` to `onCreate` caused a `NullPointerException` for me. I just pushed the code

**Comment by jaychang0917** [comment]
@csimmonsbluebook I just released a new version, pls try `1.1.17`

**Comment by csimmonsbluebook** [comment]
@jaychang0917 Your fix in `1.1.17` worked. Thanks for the help and quick responses!
