### ISSUE TITLE
Load more footer

### ISSUE THREAD

**Issue by vtproduction** [jaychang0917/SimpleRecyclerView#3]
Thanks for awesome lib !
About the auto load more feature, is it possible to add the footer (loading progress bar, etc.) ?

**Comment by jaychang0917** [comment]
In the new release `1.1.0`, you can set up load more view via `srv_loadMoreView`attribute  or `setLoadMoreView()` in java code. Pls refer to [here].(https://github.com/jaychang0917/SimpleRecyclerView/blob/master/README.md#load_more_view)
