### ISSUE TITLE
Method count issue. 

### ISSUE THREAD

**Issue by fourplay45** [jaychang0917/SimpleRecyclerView#31]
This is a nice library to use, thank you for your hard work! However the recent change has the side effect of adding lots of method count because of using Kotlin library I guess.

Can this be resolved in near the future? e.g. have a different branch which doesn't include kotlin.

**Comment by jaychang0917** [comment]
Please feel free to reopen the issue if you have any questions.

**Comment by jaychang0917** [comment]
Thanks your report, the new release `1.2.6` excluded the transitive dependencies of `kotlin-android-extensions`. 

Please feel free to reopen the issue if you have any questions.
