### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by nscherer** [jaychang0917/SimpleRecyclerView#33]
I've found two problems with the documentation.  First, the signature of `onBindViewHolder` is incorrect.  The example code shows it as 

```
onBindViewHolder(ViewHolder holder, int position, Context context, List<Object> payloads)
```

but it is actually

```
onBindViewHolder(ViewHolder holder, int position, Context context, Object payload)
```

Second, the example code uses Butterknife but does not mention anything about installing or configuring it.  If this library relies on (or is intended to be used with) Butterknife, that should be explicitly called out.  If it does not, then example code should be provided that does not require Butterknife.

**Comment by jaychang0917** [comment]
hi @nscherer , thanks your report. The correct signature of `onBindViewHolder` should be 
`onBindViewHolder(ViewHolder holder, int position, Context context, Object payload)`.

The library doesn't not rely on Butterknife.

Interested in sending a PR? Otherwise I'll do it tomorrow.
