### ISSUE TITLE
Calling setLoadingMore(false) immediately after setLoadingMore(true) breaks the state of the view

### ISSUE THREAD

**Issue by rteterin** [jaychang0917/SimpleRecyclerView#34]
When `setLoadingMore(true)` is called (which in turn calls `showLoadMoreView()`), a call to `addCell` method is added to the UI message queue and `isLoadMoreViewShown` is set to true.

If `setLoadingMore(false)` is called right after that, `removeCell` method is called immediately and `isLoadMoreViewShown` is set to false.

The problem is that at this moment the runnable that calls `addCell` is still in the message queue, therefore it will be called later. But when it's called, it adds this cell despite the fact that `isLoadMoreViewShown` is false. Now the cell is displayed, and it's not possible to hide it with another call to `setLoadingMore(false)`, because `hideLoadMoreView()` thinks that it's already hidden.

**Comment by jaychang0917** [comment]
hi @rteterin , i can't reproduce your case, and I tried the following code, the load more view will be hidden immediately as expected.
```java
recyclerView.setLoadingMore(true);
recyclerView.setLoadingMore(false);
```

**Comment by rteterin** [comment]
Hello @jaychang0917,
I created a simple app that reproduces the issue:
https://github.com/rteterin/SimpleRecyclerView_issue34_demo

**Comment by jaychang0917** [comment]
Thanks your report, the new release `1.2.7` should fix this issue.
