### ISSUE TITLE
Tapped cell moves to 1st position in recyclerview 

### ISSUE THREAD

**Issue by ravirajm** [jaychang0917/SimpleRecyclerView#35]
Hi there, first of all i'd like to say thanks for making SimpleRecyclerView. 

I noticed a strange issue recently. I've added **cell.setOnCellClickListener2** in bind data which intents to a new window. Strangely, when I come back to the RecyclerView, that tapped item/cell moves to the top of the recyclerview. It's difficult for me to put it down in words but I hope you understand.

**Comment by jaychang0917** [comment]
Pls provide a demo project.

**Comment by ravirajm** [comment]
Never-mind, it wasn't a SimpleRecyclerView issue. Thanks anyways!
