### ISSUE TITLE
AutoLoader issue

### ISSUE THREAD

**Issue by Flepsik** [jaychang0917/SimpleRecyclerView#5]
Hi man, your lib is awesome. I've found an issue with autoloader. 
I don't even know if it's a bug, autoloader doesn't work if all elements are visible. For example, I have endless list with 10 start elements on the screen. On the big screen these elements don't fill a whole screen, but I still expect recycler to call more elements to download, but it doesn't. 
But it's ok if I SimpleRecyclerView#setLoadMoreToTop() with true flag.

**Comment by jaychang0917** [comment]
Thanks your report, this issue should be fixed in the new release `1.0.4`.

**Comment by Flepsik** [comment]
Thanks !
