### ISSUE TITLE
How to add one main header for Section Header ?

### ISSUE THREAD

**Issue by peddiraju211** [jaychang0917/SimpleRecyclerView#6]

**Comment by jaychang0917** [comment]
Hi @peddiraju211 what do you means?

**Comment by peddiraju211** [comment]
@jaychang0917 Sorry for incomplete question

Can we add header view for RecyclerView at Section Header functionality ? From below screenshot I have used fixed header view. But I want to add that header view along with RecyclerView items. Any suggestions? 
![screenshot_1486991776](https://cloud.githubusercontent.com/assets/24585829/22884828/dae9d6f4-f21c-11e6-8236-af7831cf653a.png)

**Comment by jaychang0917** [comment]
What's your fixed header view mean? Sticky? Can you describe what effect you want?

**Comment by peddiraju211** [comment]
The RecyclerView first item must be a header view/inflate a view and when we scroll RecyclerView the header view also scroll along with RecyclerView items.

**Comment by jaychang0917** [comment]
You can create another cell which is your header view, and add to the recyclerview.

**Comment by jaychang0917** [comment]
New release `1.1.2` supports multiple cell type for section header now.

**Comment by jaychang0917** [comment]
If you have any further questions, please feel free to reopen this issue, thanks!

**Comment by peddiraju211** [comment]
Could you please explain more about how to add that "Header" using multiple cell type ?

**Comment by jaychang0917** [comment]
You can refer to [multi_types](https://github.com/jaychang0917/SimpleRecyclerView#multi_types).

**Comment by jaychang0917** [comment]
Your `getSectionHeaderView()` method should return your section view only, and create a new header cell, then call `recyclerview.addCell(0, headerCell)`.
