### ISSUE TITLE
Section Header first load, layout placement

### ISSUE THREAD

**Issue by ersin-ertan** [jaychang0917/SimpleRecyclerView#8]
Initial load does not show any section headers. 
Demo Code - https://github.com/ersin-ertan/Recycler @jaychang0917 

Section headers that should be visible are improperly placed in between in position, but overlapping the views without the appropriate layout/spacing.

Scrolling the header off screen or scrolling to another header will show the header correctly.

**Comment by jaychang0917** [comment]
Hi @ersin-ertan, pls provide demo code.

**Comment by jaychang0917** [comment]
I think it is due to the parent `ConstraintLayout`, try with another `ViewGroup`.

**Comment by jaychang0917** [comment]
Thanks your report, should be fixed in the new release `1.1.6`.
